### ISSUE TITLE
First glance

### ISSUE THREAD

**Issue by Womper76** [nimbian/pokepong#1]
World map music plays in battle
When you back out of the menu between wild and trainer it crashes. (see File)
Menu to select wild or trainer needs to be extended Trainer extends past box
![menu backout error](https://cloud.githubusercontent.com/assets/17578866/14757385/e1723b38-08c0-11e6-9d3f-766b2bff42e6.png)

**Comment by Wildmanbran4321** [comment]
I also had the music keep playing during battle

**Comment by nimbian** [comment]
Fixed
