### ISSUE TITLE
Selecting Wild Pokemon After Running and Music Continuing to Play

### ISSUE THREAD

**Issue by Wildmanbran4321** [nimbian/pokepong#3]
I kept selecting Rt. 28 I believe and running away because the music doesn't stop. On the fourth time running away and going back to the same place, the game closed.
![image](https://cloud.githubusercontent.com/assets/17677789/15000863/f57470b2-1160-11e6-89d8-ff36a39657ad.png)

**Comment by Wildmanbran4321** [comment]
Correction: RT 24 and 25

**Comment by nimbian** [comment]
Fixed
