### ISSUE TITLE
Ekans Wrap

### ISSUE THREAD

**Issue by Womper76** [nimbian/pokepong#7]
After he used Wrap It constricted me for i belive to turns on the third time i tried to attack it crashed
![ekans wrap](https://cloud.githubusercontent.com/assets/17578866/15092388/4c298e88-1436-11e6-88d6-c0991cd75229.png)

**Comment by Womper76** [comment]
Did not happen when i caught an ekins and used wrap on someone else

**Comment by Womper76** [comment]
Also when using wrap. it will not allow me to change attacks. Like once its constricts them it will always say ekins attack continues and do its damage. PRoblem is even after it releases and they can attack it will still when you press attack it will not give you a move option it will just say ekins attack continues.

**Comment by nimbian** [comment]
Should be fixed and pushed
